name: build Docker Img And Push to Hub

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push-to-Hub:
    name: build and push to hub
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build docker image
        run: docker build -t jakobmalmgren/puzzleimage:latest .

      - name: push image to dockerhub
        run: docker push jakobmalmgren/puzzleimage:latest
