name: check with Lint pushing to dev

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: klona repot
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: kör lint
        run: npm run lint
